### PR TITLE
Revert "Update README.markdown"

### PR DESCRIPTION
**Pull request by zachlatta**
Reverts marcuswhybrow/minecraft-server-manager#290. We're alive again!

Any additional thoughts on reverting this?

### CODE REVIEW

**Comment by marcuswhybrow** [comment]
MSM's no longer dead... but not confirmed alive: Zombie?

**Comment by endofcake** [comment]
I'd merge that, but I don't seem to have the merge rights?

**Comment by marcuswhybrow** [comment]
@endofcake Your invitation to @msmhq/collaborators is "pending". Maybe you have an email or a notification you must accept.

**Comment by endofcake** [comment]
@marcuswhybrow , cheers, must've missed this.

**Comment by renderorange** [comment]
hmm, doesn't look like I have the ability to push to master, or accept the pull request through github
````
Please make sure you have the correct access rights
and the repository exists.
````
I see myself in the collaborators list, maybe not write permissions, though?

**Comment by marcuswhybrow** [comment]
@renderorange My fault: I've added msmhq/msm to @msmhq/collaborators and @msmhq/core.

N.B. Erroneously I read "This team does not give members access to specific repositories" to mean "This team, therefore, has access to all repositories". @github could be clearer maybe.

**Comment by endofcake** [comment]
Cool, now I see I have merge rights.

**Comment by renderorange** [comment]
Thanks Marcus :)

**Pull request merged**
